### ISSUE TITLE
MAC Interface - Close / Enlarge / Reduce Window Buttons

### ISSUE THREAD

**Issue by EddieDSuza** [hoobs-org/gui#100]
<img width="896" alt="Screen Shot 2021-05-13 at 19 55 55" src="https://user-images.githubusercontent.com/52710883/118197453-5e129d80-b425-11eb-894f-6b7912c567c6.png">

Can the MAC interface follow the OS window buttons currently follows window format.

**Comment by mkellsy** [comment]
It's a cross platform electron app. Same on all platforms.
