### ISSUE TITLE
Garage Door Icon

### ISSUE THREAD

**Issue by Biggsylad** [hoobs-org/gui#103]
I would like to change the ICON for my Garage Door integrated via the Somofy Conexoon plugin, but I don't get an option. Checked the other accessories and they all have the ability to change it. Is this a limitation on the type of accessory or a bug?

**Comment by mkellsy** [comment]
The garage door accessory doesn't have an icon. It is an interactive graphic.
Lights, Switches, and Sensors are the only accessories that support icons.
