### ISSUE TITLE
Smartthings Plugin inconsistencies

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#104]
Accessories exposed through the smartthings plugin (in my case Lutron switches) have some inconsistencies:

1. No plugin and configuration button in the accessory settings (all smartthings accessories)
![image](https://user-images.githubusercontent.com/3981552/120062018-e1d7a700-c02d-11eb-8242-83145b12ef02.png)
2. [REDACTED] This issue was user error.

**Comment by mkellsy** [comment]
Can I get reproduction steps for this. I have a SmartThings setup with over 75 devices. Not a single issue. How did you set this up? Did you have any issues along the way?

**Comment by mkellsy** [comment]
This is actually an issue with the name of the plugin. This has changed so many times.
Both the platform and name should be **SmartThings-v2**

This is the only way I can reproduce this.
