### ISSUE TITLE
Bridge selection shouldn't directly install plugin

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#11]
When trying to install a plugin on an existing bridge, the expectation is that when you click an existing bridge it will highlight it then you must click the install button at the bottom of the modal. Instead it installs the plugin right away on that bridge without further confirmation. It should just select / highlight the bridge you clicked and let you click install. 

![image](https://user-images.githubusercontent.com/3981552/110572527-9517ba80-8127-11eb-8598-2f5042f560ae.png)

**Comment by mkellsy** [comment]
Done in 4.0.13
