### ISSUE TITLE
Unable to update 

### ISSUE THREAD

**Issue by Don-van-Houts** [hoobs-org/gui#113]
Good evening,
I'm unable to update to the last server version of Hoobs beta 4.0.70 & CLI version 4.0.33

see pictures
can you help me?
![IMG_6B61B3158C20-1](https://user-images.githubusercontent.com/69318655/124334763-6d49d800-db98-11eb-9ddc-98897dde777f.jpeg)
![IMG_012CFBDEE165-1](https://user-images.githubusercontent.com/69318655/124334832-a5511b00-db98-11eb-859b-a8ce88647770.jpeg)

Greetings Don.

**Comment by mkellsy** [comment]
We had to change the repo for the release.
Run this command to update the repos.

wget -qO- https://dl.hoobs.org/stable | sudo -E bash -

Then the ypdate will get the new version.
