### ISSUE TITLE
Display NPM and Homebridge Version Information

### ISSUE THREAD

**Issue by RayWilliamsII** [hoobs-org/gui#122]
**Is your feature request related to a problem? Please describe.**
It can be difficult to determine the versions of components used by HOOBS and hoobsd.  This can make it tricky when trying to work with a plugin contributor who wants details about my HOOBS environment when troubleshooting.  In most cases the contributors want to know your node.js, npm and homebridge version.  I am left to spelunk through the file system to try to extract this information.

**Describe the solution you'd like**
Add NPM and Homebridge version details to the "System Information" widget.
It would also be nice to display the HOOBS (UI) and hoobsd (server) version information as well.  Currently it shows the hoobsd version as the HOOBS version.

**Describe alternatives you've considered**
Dropping to terminal, I can run npm -v to determine the NPM version.
For homebridge, I guess I can check the CHANGELOG.md file located in /usr/lib/hoobsd/node_modules/homebridge

**Additional context**
None

**Comment by mkellsy** [comment]
Added HB version to the next release. NPM will not be added since HOOBS doesn't use it.
