### ISSUE TITLE
Setup URL Not Being Generated

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#19]
Devices are on the same network. Scanning the QR code will not pair it. It remains stuck on Connecting to Bridge. 
Also it doesn't seem to be sending any of the bridge data in the QR code. When scanned it just says 'Bridge'. No additional information. Normally it shows an identifier.

**Comment by askovi** [comment]
Adding some more details to this.
It seems like the issue only happens if the code is scanned to add the bridge to Homekit.
If you go in Homekit and look for nearby accessories by click Don't have a code or cannot scan it finds all the bridges with the proper identifiers. Then if you tap on one you can enter the pairing code (or scan the QR code using the camera) to pair it and it works.
But if you scan the code directly it cannot find it and just says connecting to 'Bridge'

**Comment by mkellsy** [comment]
Fixed in 4.0.24

**Comment by askovi** [comment]
This issue is happening again. Got a bunch of bridges and none of them can be scanned into Homekit. It just displays "Bridge" with no information. However going through the Don't have a code or cannot scan displays them properly (only after a HOOBS reboot though).

**Comment by askovi** [comment]
I also just noticed that after the reboot, while it still only shows as 'Bridge' when scanned, it now pops up the Add Anyway in Homekit and allows adding it and it works. So i'm not sure what's causing it. At the moment i'm not able to reproduce the non working state only the no identifier state.

**Comment by askovi** [comment]
Happening again now, scanning the code just shows Bridge in Homekit and clicking Add to Home just spins forever saying 'Connecting to bridge'. However it works from the dont have a code or cannot scan screen.

**Comment by mkellsy** [comment]
I think the bridges aren't being shutdown properly.

**Comment by mkellsy** [comment]
Duplicate, already reported in hoobsd.
