### ISSUE TITLE
Review Mobile Layout

### ISSUE THREAD

**Issue by ScharV** [hoobs-org/gui#2]
Additional windows, like settings or plugin configuration, doesn’t show up in foreground. They’re always on right screen side and you have to scroll to the right side to see them.
Not like in the videos.
Having those issues on MacBook Pro and iPad Pro 12.9 both with latest os and browser is Safari.

**Comment by mkellsy** [comment]
I am going to need some screenshots because they are not showing on my iPad.

**Comment by mkellsy** [comment]
Fixed
