### ISSUE TITLE
Create TV Accessory Type

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#22]
Added a TV accessory via the webos-tv plugin. Logs show it added the device but it's not appearing in the devices list

![image](https://user-images.githubusercontent.com/3981552/111057681-5d767e80-8457-11eb-86d9-b57db0cb9d3e.png)

**Comment by mkellsy** [comment]
Need to add that device type.

**Comment by mkellsy** [comment]
I need a list of plugins you are using.
Also to to troubleshoot can you do the following.
1. Disable logins (config screen, Hub section)
2. Reboot
3. Once back up. Go to the browser and enter this url http://hoobs.local/api/accessories
You may need to replace hoobs.local with the ip address.

You need to disable logins so you don't have to pass an auth token in.
You then can re-enable logins.

This data can help me find out what's happening with the accessories.

**Comment by askovi** [comment]
https://github.com/hoobs-org/gui/issues/65#issuecomment-814363002

**Comment by mkellsy** [comment]
Will need to get this directly from Homebridge
http://hoobs.local:51826/accessories

Replace the port with the WebTV Bridge port, get this from the log.

**Comment by mkellsy** [comment]
Ok @askovi the next update there will be a download data button for unknown accessories. After you upgrade to GUI 4.0.44 can you attach the data dump to this task.

**Comment by mkellsy** [comment]
Done in
GUI 4.0.55
Desktop 4.0.25
