### ISSUE TITLE
Duplicating Dashboard Accessories

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#30]
If you click the dashboard settings gear at the top and add / remove weather widgets while you're editing the dashboard, it duplicates a random existing accessory and moves all your accessories at the top and changes their size. 

![image](https://user-images.githubusercontent.com/3981552/111095472-e357ff80-8513-11eb-93ba-6c0e7ce81ca7.png)

![image](https://user-images.githubusercontent.com/3981552/111095504-f8cd2980-8513-11eb-98ef-d43417ff700d.png)

**Comment by mkellsy** [comment]
Fixed in 4.0.29

Note there may be some left over ids that would cause this again, just start fresh. While in beta we don't need to worry about upgrade paths.
