### ISSUE TITLE
Review Weather Widgets Font Size

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/gui#31]
<img width="525" alt="Screenshot 2021-03-17 at 09 27 56" src="https://user-images.githubusercontent.com/50763727/111437228-23c9a000-8703-11eb-97f0-f6887eedc0ab.png">

**Comment by mkellsy** [comment]
Bobby thinks the font is too smal

**Comment by mkellsy** [comment]
Subjective, non issue.
Reviewed on desktop and mobile.
The font is fine for the forecast.

**Comment by BobbySlope** [comment]
no it cuts sunday, the widget default size (canvas) is too small

**Comment by mkellsy** [comment]
Just resize the widget.

**Comment by BobbySlope** [comment]
on a fresh installation it does cut off sunday. i know i can resize. but it should be fully visible on a default dashboard

**Comment by mkellsy** [comment]
It's subjective to the screen size.

**Comment by mkellsy** [comment]
Made the initial size 4 units wider in 4.0.31
