### ISSUE TITLE
Review Login Fields in Safari

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/gui#32]
<img width="487" alt="Screenshot 2021-03-17 at 09 30 28" src="https://user-images.githubusercontent.com/50763727/111437499-76a35780-8703-11eb-843a-2b29226b5976.png">

**Comment by BobbySlope** [comment]
mobile on iphone the same
![IMG_C0E7AF7C2F1D-1](https://user-images.githubusercontent.com/50763727/111440685-df400380-8706-11eb-82cb-cf44aaf6ccae.jpeg)

**Comment by mkellsy** [comment]
Looks like Safari is adding a margin to the field labels.

**Comment by mkellsy** [comment]
Fixed in 4.0.31

**Comment by BobbySlope** [comment]
not solved 
im on 4.0.32

**Comment by mkellsy** [comment]
FIXED IN **GUI** 4.0.32
NOT RELEASED.

Let me do my thing, Please.
