### ISSUE TITLE
Review Accessory Layout on Mobile

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/gui#33]
you need to zoom out to get the full width screen
![IMG_3287](https://user-images.githubusercontent.com/50763727/111441102-478ee500-8707-11eb-80ce-d67020ab029b.jpg)

**Comment by mkellsy** [comment]
The mobile accessory width is set to 50% drop it to 40%.

**Comment by mkellsy** [comment]
Need more info to test.
What device?

**Comment by BobbySlope** [comment]
iphone 12 pro max

**Comment by mkellsy** [comment]
Fixed in 4.0.31
