### ISSUE TITLE
Plugin Library is not loading

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/gui#35]
<img width="1425" alt="Screenshot 2021-03-17 at 20 19 02" src="https://user-images.githubusercontent.com/50763727/111525621-1beb1980-875e-11eb-9a10-8aa38c134bf6.png">

In private browing mode it works flawlessly

**Comment by mkellsy** [comment]
Clear your browser cache cache.
Not a GUI issue. If it persists. Open an issue for the plugins site.

**Comment by BobbySlope** [comment]
works with cleared cache :)
