### ISSUE TITLE
Token Decoding is Not Supporting Unicode Characters

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/gui#37]
Reproduction  Steps
1. From the Profiles screen select a user
2. Enter Thomas Bösch or Jürg Rüdisüäli-Öbermatt in the name field
3. Save changes

Expected results
In the main menu Thomas Bösch or Jürg Rüdisüäli-Öbermatt should show properly.

Example characters: ÄÖÜäöü

Actual results
The characters are not showing properly (see example)

<img width="160" alt="Screenshot 2021-03-17 at 21 02 17" src="https://user-images.githubusercontent.com/50763727/111530888-23adbc80-8764-11eb-82ed-8caba32f1f36.png">

**Comment by mkellsy** [comment]
Fixed in 4.0.32
