### ISSUE TITLE
need login to access terminal in gui

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/gui#39]
<img width="1299" alt="Screenshot 2021-03-17 at 21 04 04" src="https://user-images.githubusercontent.com/50763727/111531083-5e175980-8764-11eb-9afa-b15b5459a68f.png">

**Comment by mkellsy** [comment]
By design,
It uses HelM
Type hoobs
Then hoobsadmin
Like SSH.

Its the same terminal at port 9090, It runs outside of HOOBSD.
Don't want 2 terminal programs running.
