### ISSUE TITLE
Connect Advanced Hub Settings with Hub Settings Dialog

### ISSUE THREAD

**Issue by oliverchapple** [hoobs-org/gui#40]
![Screenshot 2021-03-18 at 22 46 55](https://user-images.githubusercontent.com/42448591/111707542-28de3a80-883c-11eb-9be0-e69c98fda272.png)

on this picture of the config you can't put in like API key I don't know if its because the plugin has not been updated..

but you could put the api in on hoobs 3 

not sure if its a bug because there a few plugins like that 

its just said Ui path 

thanks Oliver

**Comment by mkellsy** [comment]
Done in 4.0.32

**Comment by RUHavingFun** [comment]
This seems broken.  The API keys in the Raspberry Pi image do not work.
