### ISSUE TITLE
Rename 'Clear Cache' Button

### ISSUE THREAD

**Issue by bwp91** [hoobs-org/gui#42]
I think the current wording of this button does not make it clear that it will open a window to manage cached accessories.

<img width="338" alt="Screenshot 2021-03-21 at 16 55 15" src="https://user-images.githubusercontent.com/43026681/111913527-6c1bf180-8a66-11eb-91fe-a5ed006f1059.png">

Clicking 'Restart' or 'Stop' will do exactly this when the button is clicked. A user may think, and be hesitant, that clicking 'Clear Cache' will do exactly this on click.

I would like to suggest it be renamed to something like 'Manage Cache' or 'Manage Cached Accessories' to give a better idea that clicking the button will open a modal to further manage the cached accessories.

**Comment by mkellsy** [comment]
This has been renamed to "Cache" in 4.0.32
