### ISSUE TITLE
Doubled output while updating

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/gui#43]
Update gui from hoobs.local

CLI output in popup window is doubled

<img width="704" alt="Screenshot 2021-03-22 at 18 01 21" src="https://user-images.githubusercontent.com/50763727/112028771-d4d39e80-8b38-11eb-9a8d-83abb6c26fce.png">

**Comment by mkellsy** [comment]
I was able to reproduce without reproduction steps.
Please add reproduction steps.

Fixed in 4.0.34
