### ISSUE TITLE
No Configuration screen for camera-ffmpeg plugin

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#48]
![image](https://user-images.githubusercontent.com/3981552/112883212-f8986680-909b-11eb-97c2-bbe04e7a205c.png)

Reproduction steps:
1. Install camera-ffmpeg plugin on new bridge
2. go to configuration page and it's empty
3.Nothing special in the logs. 
![image](https://user-images.githubusercontent.com/3981552/112883351-2ed5e600-909c-11eb-9c9c-cd6d455bfbec.png)

Could this be because camera-ffmpeg is bridged separately? (each camera shows as a bridge in homekit)

**Comment by mkellsy** [comment]
Schema is missing type object. This is a common issue found in incomplete schemas. I will add a check for it and add it if it is missing.

**Comment by mkellsy** [comment]
Fixed in 4.0.38
