### ISSUE TITLE
CPU Temp always in Celsius

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#49]
Changing the temperature units into Fahrenheit doesn't affect the CPU temp widget which remains in Celsius. 
Additionally the ℃ character looks like a serif C, doesn't seem to be affected by font property. 

![image](https://user-images.githubusercontent.com/3981552/113083283-f290ab80-91a9-11eb-85e9-dfb0e06a3ec2.png)

**Comment by mkellsy** [comment]
By design. I will not use the unicode character for deg C.
