### ISSUE TITLE
Allow Room Accessories on Dashboard

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#53]
Would make sense to have the All Lights and All Off for the entire house available on the dashboard.

**Comment by mkellsy** [comment]
After an in-depth look into this, I realize it is hard to do. The room accessories are dynamic in nature, and pose issues for the dashboard when the room's accessories change. It also requires to load multiple rooms at the same time from one screen.

After initial testing, this majorly slows down the dashboard. This will require some deep, HOOBSD, HB, and SDK changes.

I am closing this with the label "backburner" to get it out of the pipeline. I will revisit this when time permits.
