### ISSUE TITLE
Dashboard accessories moving on their own

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#55]
I arranged my dashboard nicely how I wanted it including accessory tiles. Reized, re-arranged, etc.
Then I went to add more accessories to the dashboard from the accessory page. When adding first one, it just adds it at the top of the dashboard and nothing else moves. If you don't edit the dashboard at this time to move the latest accessory somewhere else, and add a 2nd and 3rd accessory to dashboard, other accessories that were previously arranged will jump to the top. Screenshot for reference. The accessories on the left were just added, the ones on the right jumped there on their own. 

 
![image](https://user-images.githubusercontent.com/3981552/113243865-d2ccb680-9281-11eb-9f1e-220113869028.png)

**Comment by askovi** [comment]
This also just happened when removing an accessory from the dashboard (latest added that was still in the top left corner). A bunch of random accessories that were already nicely arranged just jumped to the top. 

Then when I added another accessory to the dashboard, some jumped back, very weird behavior.

**Comment by askovi** [comment]
The system details tile also jumped so it's not only affecting the accessories tiles

**Comment by mkellsy** [comment]
This is a 3rd party component called Gridster. This will happen when adding because it re-indexes the widgets on edit. It will float down and to the left.
