### ISSUE TITLE
Display Plugin Name in Accessory Dialog

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#56]
In the accessory settings modal there is a plugin section already. It would be really useful to show the actual plugin that exposes that accessory without having to click on the Configuration button. I have many different accessories that are for the same area (eg. Front Door could be contact sensor, camera, motion etc) that are exposed by different plugins. 
![image](https://user-images.githubusercontent.com/3981552/113244715-9437fb80-9283-11eb-85e5-870bd063da1d.png)

**Comment by mkellsy** [comment]
Done in
GUI 4.0.39
Desktop 4.0.9
