### ISSUE TITLE
Add Overflow to Bridge List in Bridges Dialog

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#58]
If you have multiple bridges and want to install a new plugin, the modal buttons are pushed below the content and become hidden. They should be static and always remain on top.
Maybe the bridge list should have 2 or 3 columns instead. 

![image](https://user-images.githubusercontent.com/3981552/113247278-a9fbef80-9288-11eb-90e2-727e37209284.png)

**Comment by mkellsy** [comment]
Fixed in
GUI 4.0.39
Desktop 4.0.9
