### ISSUE TITLE
Minor Spelling Error

### ISSUE THREAD

**Issue by ballakers** [hoobs-org/gui#59]
Didn't want to be this guy lol but just want to help and cover off everything.

When you click the three dot menu in top right (takes a few seconds to load and show the user name) it says "Loged In As" when it should say "Logged in as". Just need an extra g (everyone wants an extra G right?!?!). I know this is very low on the issue list but an issue none the less.

**Comment by mkellsy** [comment]
Fixed in 4.0.39
