### ISSUE TITLE
Delete button in the config schema should prompt for confirmation

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#61]
When clicking the trash icon in config schema elements, it currently deletes the object right away (granted you need to save changes for this to apply but it could confuse some users if the click it by accident). Every delete button should contain a confirmation modal. 

Additionally, the Add and Delete (Plus and Trash icons) in the config schema should maybe contain supporting text as to what they will add or delete. In some cases it can become confusing such as here: 

![image](https://user-images.githubusercontent.com/3981552/113342453-82df0580-92fc-11eb-8bc8-c0b8a122f860.png)

**Comment by mkellsy** [comment]
Concept is good, but this is a 3rd party Vue plugin.
