### ISSUE TITLE
Don't Show UI Plugin if Bridge is not Running

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#62]
Tried to Link account in the Ring plugin config. The bridge was apparently stopped automatically due to the port conflict issue (https://github.com/hoobs-org/hoobsd/issues/26)
This was no apparent to me as I just installed the plugin on a new bridge. Clicked Link Account and the modal was blank / white. This was in the browser logs: 
![image](https://user-images.githubusercontent.com/3981552/113380576-95802b80-934a-11eb-93da-44aedea07b36.png)

**Comment by mkellsy** [comment]
Plugins don't show if they are not running.
Fixed in
GUI 4.0.39
Desktop 4.0.9
