### ISSUE TITLE
Cannot access terminal through UI properly

### ISSUE THREAD

**Issue by saiajin** [hoobs-org/gui#63]
I am accessing Hoobs via my MAC and when I try to get the terminal I get:

<img width="1231" alt="Screen Shot 2021-04-02 at 9 56 05 AM" src="https://user-images.githubusercontent.com/71667075/113436506-ac01a380-9399-11eb-8865-48419eb66f98.png">

**Comment by askovi** [comment]
That’s normal. It’s the same terminal as the recovery terminal. Just login with hoobs // hoobsadmin

**Comment by saiajin** [comment]
Gotcha.. I never had to login b4 via the WEB UI  .. Thanx!

**Comment by mkellsy** [comment]
The terminal is actually hosted on a different port then HOOBS. It's available even if HOOBS is not running. You can access it at http://hoobs.local:9090. This is why it needs a login now.

No more SSH!
