### ISSUE TITLE
Accessory Dashboard Widget Sizing

### ISSUE THREAD

**Issue by Biggsylad** [hoobs-org/gui#64]
Added Nest Thermostat Acc along with Ring Rear and Front Spotlights, looks perfect on Ipad, but not so good on PC. All wording on the accessories on PC are cut in half. I did resize them but made them bigger. Looked ok before I tried on a IPAD

**Comment by Biggsylad** [comment]
![Capture](https://user-images.githubusercontent.com/81716268/113457056-be65f680-9406-11eb-9591-ddd033be998a.PNG)

**Comment by mkellsy** [comment]
Added new CSS aspect ratio and object fit directives
Fixed in
GUI 4.0.39
Desktop 4.0.9
