### ISSUE TITLE
Check Updates Screen

### ISSUE THREAD

**Issue by Biggsylad** [hoobs-org/gui#66]
Hi

This might be by design, but I would imagine you need a close or ok button rather than a cancel button after you have checked for updates. Very minor, but the implication is it could be still checking for updates and you are cancelling a process.......

![Capture](https://user-images.githubusercontent.com/81716268/113781711-00ee4280-9729-11eb-9af0-b9f9855acb74.PNG)

**Comment by mkellsy** [comment]
GUI 4.0.39
Desktop 4.0.9
