### ISSUE TITLE
Add Plugin Names to Upgrade Dialog

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#68]
While the update all plugins option from the dashboard is nice, finding information about which plugin needs updating and what the updates are is very difficult. 

If you run 1 plugin per bridge and there is a plugin update while you got 10 bridges running, you currently have to click through each bridge from the plugin page, then click on the plugin on that bridge just to see if that plugin has an update available. Then there is no information about the release notes of that update. 

Proposed changes:
1. Add information about which plugins have updates available on this screen:
![image](https://user-images.githubusercontent.com/3981552/113970738-61eb4880-9805-11eb-9bad-252edbc16549.png)
2. Make each plugin name on that window clickable and link to that plugin page
3. This update button should prompt a dialog with release notes pulled from github and a confirmation button to begin the update:
![image](https://user-images.githubusercontent.com/3981552/113970863-a7a81100-9805-11eb-9816-6c9c0e0962a5.png)

4. When a plugin update is available, there should be a notification in the notification center about it with the name of the plugin and a link to go to that plugin page
5.  On the plugins page there should be some sort of superscript number with how many updates are available for that bridge 
![image](https://user-images.githubusercontent.com/3981552/113971285-7da31e80-9806-11eb-8b5a-f2e1ffa94803.png)

6. On the installed plugins page for each bridge, the plugins should also have an indication if a plugin update is available:
![image](https://user-images.githubusercontent.com/3981552/113971239-649a6d80-9806-11eb-82fc-e6290a398371.png)

**Comment by mkellsy** [comment]
Adding a plugin upgrade status on the plugin screen would be too slow and not saleable.
I did list the plugins on the upgrade screen, it is fast and cheap since the information was already there.

Done in
GUI 4.0.39
Desktop 4.0.9
