### ISSUE TITLE
Add Word Wrapping for Log on Mobile

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/gui#69]
The log view on mobile devices do not appear to auto size within the web iframe (see screenshot)![image](https://user-images.githubusercontent.com/23066923/114603284-8b70fd80-9c65-11eb-9385-908f20858e1d.png)

**Comment by mkellsy** [comment]
I tried to word wrap this and it makes it hard to know what goes with what.
The vertical and horizontal scrolling keeps the log inline.

I decided that wrapping this is not desired.

**Comment by themick4u** [comment]
Is it word wrapping or would it be auto-sized... like when building web pages you have the option to tell it auto instead of fixed

**Comment by mkellsy** [comment]
Auto font sizing is not a thing on web interfaces. I did set the font size smaller for mobile, I also removed the timestamps and wrap the message to prevent vertical scrolling.

Done in
GUI 4.0.44

**Comment by themick4u** [comment]
Mike, logs look great on mobile now, thanks! 
Figured some positive comments here might offset the constant barrage of otherwise
