### ISSUE TITLE
Handle Blank Location on All Weather Widgets

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#7]
Enabling the weather widgets from the dashboard settings crashed the whole service and had to wait 10 seconds for hoobs.local to come back up and relogin. Some browser errors:

![image](https://user-images.githubusercontent.com/3981552/110229182-96ea3f80-7ed5-11eb-9550-2b980b5bacce.png)

**Comment by askovi** [comment]
This also deleted my location settings for the weather and the weather rectangle is empty again on the dashboard

**Comment by mkellsy** [comment]
Fixed
