### ISSUE TITLE
Update dialog needs to close after update completes

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#70]
Currently after system update is done, the dialog remains like this:
![image](https://user-images.githubusercontent.com/3981552/114608553-ce35d400-9c6b-11eb-8eaa-bbada51cbbd8.png)
Refreshing the page shows that the update was completed.

**Comment by mkellsy** [comment]
It does close. Unable to reproduce.

**Comment by askovi** [comment]
For the past 4 updates including to 4.0.43 it never closed. Try changing tabs while the update is happening to reproduce.

**Comment by mkellsy** [comment]
Can't fix it if you are the only one seeing it and I am unable to reproduce.
