### ISSUE TITLE
Interface became unresponsive and crashed after installing the tp-link plugin

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#8]
Installed the plugin on a new bridge and moved away from the config page after it installed. Interface crashed. 
Some browser logs:
![image](https://user-images.githubusercontent.com/3981552/110229329-ae75f800-7ed6-11eb-92f1-d834dcce079b.png)

**Comment by askovi** [comment]
After it came back online I tried to access the tplink bridge from the plugins page and it crashed again

**Comment by askovi** [comment]
This rendered the whole system unstable, couldn't even navigate via ssh, required a reboot. Then it happened again once that page was accessed

**Comment by mkellsy** [comment]
Fixed

**Comment by mkellsy** [comment]
Same cause as #4
