### ISSUE TITLE
Accessories will not show

### ISSUE THREAD

**Issue by mstahl79** [hoobs-org/gui#80]
When clicking on the accessories link, I get the HOOBS logo and nothing comes up

**Comment by mkellsy** [comment]
Fixed in GUI 4.0.47

**Comment by mstahl79** [comment]
I'm running 4.0.48

**Comment by mkellsy** [comment]
The GUI is versioned differently.
You are running Server (HOOBSD) 4.0.48.
The GUI is only at 4.0.45.

You can see the details of the versions of each component by running this command
```
sudo hbs system versions
```

**Comment by mstahl79** [comment]
How would i get the GUI up to 4.0.47 to fix this?

    On Wednesday, April 21, 2021, 2:05:27 PM EDT, Michael Kellsy ***@***.***> wrote:  
 
 


The GUI is versioned differently.
You are running Server (HOOBSD) 4.0.48.
The GUI is only at 4.0.45.

You can see the details of the versions of each component by running this command
sudo hbs system versions

**Comment by mkellsy** [comment]
When I release it.

In the meantime try
1. Clearing the hub cache **Menu -> Hub Settings -> Clear Cache**
2. Clear bridge cache **Bridge Screen -> Cache -> Clear** Repeat for each bridge
3. You many need to re-flash with a fresh image https://repo.hoobs.org/image/hoobs-latest.zip
