### ISSUE TITLE
Review Camera Live Streams

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#86]
I have 2 Wyze cams a v2 and a v2 pan. Both work perfectly and fast in homekit however in the HOOBS interface only the snapshot shows, no live stream. When I flip the live stream switch a play button appears on a black screen and clicking play nothing happens, the black screen remains. No entries in the logs either like when you start the stream in Homekit which shows up in the logs. 
I tried both bridged and unbridged and the same thing happens.

**Comment by askovi** [comment]
The stream api page doesn't load at all: 
http://hoobshome.local/api/accessory/cameraffmpegbridge/98a17acd-5775-d065-c117-04af26bd0805/stream

**Comment by mkellsy** [comment]
The Wyze streams start after a bit. Not much we can do ffmpeg is a bit slow.

**Comment by askovi** [comment]
I have 2 of them and none of them stream at all. I waited minutes after clicking play. I also tried different config settings, nothing changes.

**Comment by askovi** [comment]
I also tried different browsers and it's the same. The stream link doesn't actually load at all

**Comment by mkellsy** [comment]
Marking this done in
GUI 4.0.49
Desktop 4.0.19

**Comment by askovi** [comment]
This is still not working for me. I see a loading icon now when pressing play on live which I didn't see before. The stream api url still doesn't load at all. I tried reflashing latest img and updating to latest version on a new device and same results. Here are the accessory characteristics:

```
not helpful
```

**Comment by mkellsy** [comment]
I tested this on may devices. Chrome, Edge, Safari. iOS, iPad, Windows, Linux, Mac. All works consistent.
It's gota be something else.

Here's some things to try.
open the RTSP stream in VLC. Get this from your config.
Does VLC work?

Then using VLC open the MP4 stream.
http://hoobs.local/api/accessory/cameraffmpegbridge/91706cef-07d1-5061-f9b8-bf1a0bc99d31/stream
Does it work?

**Comment by askovi** [comment]
Yes it works fine in VLC. It also works fine in Homekit.
No that /stream URL does not load at all. It just spins forever 

![image](https://user-images.githubusercontent.com/3981552/115920798-a9e6ae00-a448-11eb-9648-d4bb187ad509.png)

**Comment by mkellsy** [comment]
Open the /stream URL in VLC.

Browser's can't load a video stream directly.

**Comment by askovi** [comment]
Works now. Seems to have been related to a network issue.
