### ISSUE TITLE
Dashboard Widgets

### ISSUE THREAD

**Issue by ssuro** [hoobs-org/gui#93]
Widgets added to Dashboard do not display properly. 
![Screen Shot 2021-04-28 at 3 59 39 PM](https://user-images.githubusercontent.com/49602347/116478103-cd3f9d80-a83a-11eb-9435-7f60bfad0cfb.png)

**Comment by mkellsy** [comment]
Try clearing your cache.
Also is Edge upgraded?

**Comment by mkellsy** [comment]
You could also try the desktop app.

Windows
https://repo.hoobs.org/source/hoobs-desktop-latest.exe

Mac
https://repo.hoobs.org/source/hoobs-desktop-latest.dmg

**Comment by ssuro** [comment]
Just Trying out the beta.   Thought I’d submit the gui anomaly.    I cleared the cache and rebooted the server … widgets look the same.   Tried both Safari and Firefox (on a Mac).  

Thanks for the desktop app … I’ll give that a go.

**Comment by ssuro** [comment]
Looks like the widgets display the same in the desktop app and shown in my screenshot of the web browser dashboard.      

I now realize that you can re-size and reposition the widgets which clears up the distorted view of the data I was getting on the widget.
