### ISSUE TITLE
Not Able to Close Logger Dialogs on Errors

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/gui#97]
as npm was down for some minutes today i tried to install the ring plugin to see what happens
here are the screenshots

![IMG_3740](https://user-images.githubusercontent.com/50763727/117287979-49edff80-ae6b-11eb-9025-84ca217b5fd0.jpg)
![IMG_3741](https://user-images.githubusercontent.com/50763727/117287990-4ce8f000-ae6b-11eb-9fb2-9954b1e6fac6.jpg)

Using windows app 
theres no way to escape the screen when an error occurs

if there is an close windows X on the top right of the popup that would be great.
but if a user closes the popup window the command should stay running in background

**Comment by mkellsy** [comment]
The close button is hidden for a reason. I traced every path, and the dialog will close with a success or it will alert an error.
Yarn during network disruptions, will retry, a lot. It can take up to 10 minutes for Yarn to give up. Once it does, the error will show.

To correct this, I am changing the window controls to be persistent. This is already in a different issue, so I am closing this one.
